SELECT
    PG.IDSUBPRODUTO AS CODIGO_PRODUTO,
    P.DESCRCOMPRODUTO AS DESCRICAO,
    S.DESCRSECAO AS SECAO
FROM DBA.PRODUTO_GRADE PG
INNER JOIN DBA.PRODUTO P
    ON P.IDPRODUTO = PG.IDPRODUTO
LEFT JOIN DBA.SECAO S
    ON S.IDSECAO = P.IDSECAO
WHERE
    PG.FLAGINATIVO = 'F'
    AND (
        UPPER(P.DESCRCOMPRODUTO) LIKE UPPER(?)
        OR CAST(PG.IDSUBPRODUTO AS VARCHAR(20)) = ?
    )
ORDER BY P.DESCRCOMPRODUTO
FETCH FIRST 30 ROWS ONLY;
