WITH VENDAS AS (
    SELECT
        N.IDCLIFOR,
        EA.IDPLANILHA,
        EA.DTMOVIMENTO,
        CASE
            WHEN COALESCE(EA.NUMSEQUENCIAKIT,0) <= 0 AND OI.TIPOMOVIMENTO <> 'E'
            THEN EA.VALTOTLIQUIDO
            ELSE 0
        END AS VALORVENDA
    FROM DBA.ESTOQUE_ANALITICO EA
    INNER JOIN DBA.NOTAS_ENTRADA_SAIDA NES
        ON NES.IDEMPRESA = EA.IDEMPRESA
        AND NES.IDPLANILHA = EA.IDPLANILHA
        AND NES.DTMOVIMENTO = EA.DTMOVIMENTO
    INNER JOIN DBA.NOTAS N
        ON N.IDEMPRESA = EA.IDEMPRESA
        AND N.IDPLANILHA = EA.IDPLANILHA
        AND N.FLAGNOTACANCEL = 'F'
    INNER JOIN DBA.OPERACAO_INTERNA OI
        ON OI.IDOPERACAO = EA.IDOPERACAO
        AND OI.FLAGMOVPRODUTOS = 'T'
        AND OI.TIPOMOVIMENTO IN ('V','E')
    WHERE
        EA.IDVENDEDOR IN ({{VENDEDORES}})
        AND EA.IDOPERACAO <> 1301
        AND NES.TIPOITEMCATEGORIA NOT IN ('D8')
        AND N.IDCLIFOR IS NOT NULL
),
RESUMO_PERIODO AS (
    SELECT
        IDCLIFOR,
        CAST(SUM(VALORVENDA) AS NUMERIC(15,2)) AS TOTAL_COMPRADO,
        COUNT(DISTINCT IDPLANILHA) AS PEDIDOS
    FROM VENDAS
    WHERE DTMOVIMENTO BETWEEN ? AND ?
    GROUP BY IDCLIFOR
),
ULTIMA_COMPRA AS (
    SELECT
        IDCLIFOR,
        MAX(DTMOVIMENTO) AS DTULTIMACOMPRA
    FROM VENDAS
    GROUP BY IDCLIFOR
)
SELECT
    CF.IDCLIFOR,
    CF.NOME AS CLIENTE,
    CF.FLAGINATIVO,
    COALESCE(RP.TOTAL_COMPRADO, 0) AS TOTAL_COMPRADO,
    COALESCE(RP.PEDIDOS, 0) AS PEDIDOS,
    CASE
        WHEN COALESCE(RP.PEDIDOS, 0) = 0 THEN 0
        ELSE CAST(RP.TOTAL_COMPRADO / RP.PEDIDOS AS NUMERIC(15,2))
    END AS TICKET_MEDIO,
    UC.DTULTIMACOMPRA AS ULTIMA_COMPRA,
    DAYS(CURRENT DATE) - DAYS(UC.DTULTIMACOMPRA) AS DIAS_SEM_COMPRAR
FROM DBA.CLIENTE_FORNECEDOR CF
INNER JOIN ULTIMA_COMPRA UC
    ON UC.IDCLIFOR = CF.IDCLIFOR
LEFT JOIN RESUMO_PERIODO RP
    ON RP.IDCLIFOR = CF.IDCLIFOR
ORDER BY TOTAL_COMPRADO DESC;
