WITH VENDAS AS (
    SELECT
        N.IDCLIFOR,
        EA.DTMOVIMENTO,
        CASE
            WHEN COALESCE(EA.NUMSEQUENCIAKIT,0) <= 0 AND OI.TIPOMOVIMENTO <> 'E'
            THEN EA.VALTOTLIQUIDO
            ELSE 0
        END AS VALORVENDA
    FROM DBA.ESTOQUE_ANALITICO EA
    INNER JOIN DBA.NOTAS_ENTRADA_SAIDA NES
        ON NES.IDEMPRESA = EA.IDEMPRESA
        AND NES.IDPLANILHA = EA.IDPLANILHA
        AND NES.DTMOVIMENTO = EA.DTMOVIMENTO
    INNER JOIN DBA.NOTAS N
        ON N.IDEMPRESA = EA.IDEMPRESA
        AND N.IDPLANILHA = EA.IDPLANILHA
        AND N.FLAGNOTACANCEL = 'F'
    INNER JOIN DBA.OPERACAO_INTERNA OI
        ON OI.IDOPERACAO = EA.IDOPERACAO
        AND OI.FLAGMOVPRODUTOS = 'T'
        AND OI.TIPOMOVIMENTO IN ('V','E')
    WHERE
        EA.IDVENDEDOR IN ({{VENDEDORES}})
        AND EA.IDOPERACAO <> 1301
        AND NES.TIPOITEMCATEGORIA NOT IN ('D8')
        AND N.IDCLIFOR IS NOT NULL
),
RESUMO_PERIODO AS (
    -- "Relevante" = faturou mais que R$ 5.000 no período (ajuste o HAVING conforme a regra de negócio).
    SELECT
        IDCLIFOR,
        CAST(SUM(VALORVENDA) AS NUMERIC(15,2)) AS TOTAL_COMPRADO
    FROM VENDAS
    WHERE DTMOVIMENTO BETWEEN ? AND ?
    GROUP BY IDCLIFOR
    HAVING SUM(VALORVENDA) > 5000
),
ULTIMA_COMPRA AS (
    SELECT
        IDCLIFOR,
        MAX(DTMOVIMENTO) AS DTULTIMACOMPRA
    FROM VENDAS
    GROUP BY IDCLIFOR
)
SELECT
    CF.IDCLIFOR,
    CF.NOME AS CLIENTE,
    RP.TOTAL_COMPRADO,
    UC.DTULTIMACOMPRA AS ULTIMA_COMPRA,
    DAYS(CURRENT DATE) - DAYS(UC.DTULTIMACOMPRA) AS DIAS_SEM_COMPRAR
FROM RESUMO_PERIODO RP
INNER JOIN DBA.CLIENTE_FORNECEDOR CF
    ON CF.IDCLIFOR = RP.IDCLIFOR
INNER JOIN ULTIMA_COMPRA UC
    ON UC.IDCLIFOR = RP.IDCLIFOR
ORDER BY DIAS_SEM_COMPRAR DESC
FETCH FIRST 20 ROWS ONLY;
