SELECT
    COUNT(DISTINCT N.IDCLIFOR) AS CLIENTES_ATIVOS
FROM DBA.ESTOQUE_ANALITICO EA
INNER JOIN DBA.NOTAS_ENTRADA_SAIDA NES
    ON NES.IDEMPRESA = EA.IDEMPRESA
    AND NES.IDPLANILHA = EA.IDPLANILHA
    AND NES.DTMOVIMENTO = EA.DTMOVIMENTO
INNER JOIN DBA.NOTAS N
    ON N.IDEMPRESA = EA.IDEMPRESA
    AND N.IDPLANILHA = EA.IDPLANILHA
    AND N.FLAGNOTACANCEL = 'F'
INNER JOIN DBA.OPERACAO_INTERNA OI
    ON OI.IDOPERACAO = EA.IDOPERACAO
    AND OI.FLAGMOVPRODUTOS = 'T'
    AND OI.TIPOMOVIMENTO IN ('V','E')
WHERE
    EA.IDVENDEDOR IN ({{VENDEDORES}})
    AND EA.IDOPERACAO <> 1301
    AND NES.TIPOITEMCATEGORIA NOT IN ('D8');
