WITH MOVIMENTOS AS (
    SELECT
        EA.IDPRODUTO,
        CASE
            WHEN COALESCE(EA.NUMSEQUENCIAKIT,0) <= 0 AND OI.TIPOMOVIMENTO <> 'E'
            THEN EA.VALTOTLIQUIDO
            ELSE 0
        END AS VALORVENDA,
        CASE
            WHEN OI.TIPOMOVIMENTO = 'E' THEN EA.VALTOTLIQUIDO
            ELSE 0
        END AS VALORDEVOLUCAO
    FROM DBA.ESTOQUE_ANALITICO EA
    INNER JOIN DBA.NOTAS_ENTRADA_SAIDA NES
        ON NES.IDEMPRESA = EA.IDEMPRESA
        AND NES.IDPLANILHA = EA.IDPLANILHA
        AND NES.DTMOVIMENTO = EA.DTMOVIMENTO
    INNER JOIN DBA.NOTAS N
        ON N.IDEMPRESA = EA.IDEMPRESA
        AND N.IDPLANILHA = EA.IDPLANILHA
        AND N.FLAGNOTACANCEL = 'F'
    INNER JOIN DBA.OPERACAO_INTERNA OI
        ON OI.IDOPERACAO = EA.IDOPERACAO
        AND OI.FLAGMOVPRODUTOS = 'T'
        AND OI.TIPOMOVIMENTO IN ('V','E')
    WHERE
        EA.IDVENDEDOR IN ({{VENDEDORES}})
        AND EA.IDOPERACAO <> 1301
        AND NES.TIPOITEMCATEGORIA NOT IN ('D8')
        AND EA.DTMOVIMENTO BETWEEN ? AND ?
),
TOTAIS AS (
    -- SUM() precisa ser convertido para DECIMAL explicitamente antes da divisão:
    -- dividir direto o resultado de dois SUM(CASE...) trunca a escala pra 0 no DB2.
    SELECT
        CAST(SUM(VALORVENDA) AS DECIMAL(15,6)) AS TOTAL_VENDA,
        CAST(SUM(VALORDEVOLUCAO) AS DECIMAL(15,6)) AS TOTAL_DEVOL,
        COUNT(DISTINCT IDPRODUTO) AS PRODUTOS_VENDIDOS
    FROM MOVIMENTOS
)
SELECT
    CAST(TOTAL_VENDA AS NUMERIC(15,2)) AS FATURAMENTO_TOTAL,
    PRODUTOS_VENDIDOS,
    CAST(TOTAL_DEVOL AS NUMERIC(15,2)) AS DEVOLUCOES_VALOR,
    CASE
        WHEN TOTAL_VENDA = 0 THEN 0
        ELSE CAST(TOTAL_DEVOL / TOTAL_VENDA AS NUMERIC(9,4))
    END AS DEVOLUCOES_PERCENTUAL
FROM TOTAIS;
