WITH VENDAS AS (
    SELECT
        N.IDCLIFOR,
        EA.IDPLANILHA,
        CASE
            WHEN COALESCE(EA.NUMSEQUENCIAKIT,0) <= 0 AND OI.TIPOMOVIMENTO <> 'E'
            THEN EA.VALTOTLIQUIDO
            ELSE 0
        END AS VALORVENDA
    FROM DBA.ESTOQUE_ANALITICO EA
    INNER JOIN DBA.NOTAS_ENTRADA_SAIDA NES
        ON NES.IDEMPRESA = EA.IDEMPRESA
        AND NES.IDPLANILHA = EA.IDPLANILHA
        AND NES.DTMOVIMENTO = EA.DTMOVIMENTO
    INNER JOIN DBA.NOTAS N
        ON N.IDEMPRESA = EA.IDEMPRESA
        AND N.IDPLANILHA = EA.IDPLANILHA
        AND N.FLAGNOTACANCEL = 'F'
    INNER JOIN DBA.OPERACAO_INTERNA OI
        ON OI.IDOPERACAO = EA.IDOPERACAO
        AND OI.FLAGMOVPRODUTOS = 'T'
        AND OI.TIPOMOVIMENTO IN ('V','E')
    WHERE
        EA.IDVENDEDOR IN ({{VENDEDORES}})
        AND EA.IDOPERACAO <> 1301
        AND NES.TIPOITEMCATEGORIA NOT IN ('D8')
        AND EA.DTMOVIMENTO BETWEEN ? AND ?
        AND N.IDCLIFOR IS NOT NULL
),
RESUMO AS (
    SELECT
        IDCLIFOR,
        CAST(SUM(VALORVENDA) AS NUMERIC(15,2)) AS TOTAL,
        COUNT(DISTINCT IDPLANILHA) AS PEDIDOS
    FROM VENDAS
    GROUP BY IDCLIFOR
)
SELECT
    CF.NOME AS CLIENTE,
    R.TOTAL,
    R.PEDIDOS,
    CASE
        WHEN R.PEDIDOS = 0 THEN 0
        ELSE CAST(R.TOTAL / R.PEDIDOS AS NUMERIC(15,2))
    END AS TICKET_MEDIO
FROM RESUMO R
INNER JOIN DBA.CLIENTE_FORNECEDOR CF
    ON CF.IDCLIFOR = R.IDCLIFOR
ORDER BY R.TOTAL DESC
FETCH FIRST 10 ROWS ONLY;
