WITH ULTIMA_DATA AS (
    SELECT
        IDEMPRESA,
        MAX(DTMOVIMENTO) AS DTMOVIMENTO
    FROM DBA.CONTABIL_SALDO
    WHERE IDEMPRESA IN ({{FILIAIS}})
      AND DTMOVIMENTO <= ?
    GROUP BY IDEMPRESA
),
SALDOS AS (
    SELECT
        CASE
            WHEN PC.CLASSIFICACAO LIKE '111%' THEN 'DISPONIVEL'
            WHEN PC.CLASSIFICACAO LIKE '112%' THEN 'VALORES_A_RECEBER'
            WHEN PC.CLASSIFICACAO LIKE '113%' THEN 'ESTOQUES'
            WHEN PC.CLASSIFICACAO LIKE '114%' THEN 'DESPESAS_ANTECIPADAS'
            WHEN PC.CLASSIFICACAO LIKE '121%' THEN 'REALIZAVEL_LONGO_PRAZO'
            WHEN PC.CLASSIFICACAO LIKE '123%' THEN 'INVESTIMENTOS'
            WHEN PC.CLASSIFICACAO LIKE '124%' THEN 'IMOBILIZADO'
            WHEN PC.CLASSIFICACAO LIKE '211%' THEN 'OBRIGACOES_COM_TERCEIROS'
            WHEN PC.CLASSIFICACAO LIKE '221%' THEN 'EXIGIVEL_LONGO_PRAZO'
            WHEN PC.CLASSIFICACAO LIKE '241%' THEN 'CAPITAL_SOCIAL'
            WHEN PC.CLASSIFICACAO LIKE '242%' THEN 'RESERVAS'
            WHEN PC.CLASSIFICACAO LIKE '243%' THEN 'PREJUIZOS_ACUMULADOS'
        END AS LINHA,
        CS.VALSALDOATUAL AS VALOR
    FROM DBA.CONTABIL_SALDO CS
    INNER JOIN ULTIMA_DATA UD
        ON UD.IDEMPRESA = CS.IDEMPRESA
        AND UD.DTMOVIMENTO = CS.DTMOVIMENTO
    INNER JOIN DBA.CONTABIL_PLANO_CONTAS PC
        ON PC.IDCTACONTABIL = CS.IDCTACONTABIL
        AND PC.TIPOCTACONTABIL = 'A'
    WHERE CS.IDEMPRESA IN ({{FILIAIS}})
      AND (PC.CLASSIFICACAO LIKE '111%' OR PC.CLASSIFICACAO LIKE '112%' OR PC.CLASSIFICACAO LIKE '113%'
           OR PC.CLASSIFICACAO LIKE '114%' OR PC.CLASSIFICACAO LIKE '121%' OR PC.CLASSIFICACAO LIKE '123%'
           OR PC.CLASSIFICACAO LIKE '124%' OR PC.CLASSIFICACAO LIKE '211%' OR PC.CLASSIFICACAO LIKE '221%'
           OR PC.CLASSIFICACAO LIKE '241%' OR PC.CLASSIFICACAO LIKE '242%' OR PC.CLASSIFICACAO LIKE '243%')
)
SELECT
    LINHA,
    CAST(SUM(VALOR) AS NUMERIC(15,2)) AS VALOR
FROM SALDOS
WHERE LINHA IS NOT NULL
GROUP BY LINHA
ORDER BY LINHA;
