WITH BASE AS (
    SELECT
        CR.IDCLIFOR,
        VARCHAR_FORMAT(CR.DTMOVIMENTO, 'YYYY-MM') AS MES,
        CR.VALTITULO AS VALOR
    FROM DBA.CONTAS_RECEBER CR
    WHERE CR.IDEMPRESA IN ({{FILIAIS}})
      AND CR.DTMOVIMENTO BETWEEN ? AND ?
),
CLIENTE_MESES AS (
    SELECT IDCLIFOR, COUNT(DISTINCT MES) AS QTD_MESES
    FROM BASE
    GROUP BY IDCLIFOR
)
SELECT
    B.MES,
    CASE WHEN CM.QTD_MESES >= 2 THEN 'Recorrentes' ELSE 'Nao recorrentes' END AS TIPO,
    CAST(SUM(B.VALOR) AS NUMERIC(15,2)) AS VALOR,
    COUNT(DISTINCT B.IDCLIFOR) AS QTD_CLIENTES
FROM BASE B
INNER JOIN CLIENTE_MESES CM
    ON CM.IDCLIFOR = B.IDCLIFOR
GROUP BY B.MES, CASE WHEN CM.QTD_MESES >= 2 THEN 'Recorrentes' ELSE 'Nao recorrentes' END
ORDER BY B.MES, TIPO;
