SELECT
    CF.NOME AS FORNECEDOR,
    COUNT(*) AS TITULOS,
    CAST(SUM(CP.VALTITULO - COALESCE(CP.SUMVALPAGAMENTOTITULO, 0) - COALESCE(CP.SUMVALDESCCONCEDIDOTITULO, 0)) AS NUMERIC(15,2)) AS SALDO,
    MAX(CASE WHEN CP.DTVENCIMENTO < CURRENT DATE THEN DAYS(CURRENT DATE) - DAYS(CP.DTVENCIMENTO) ELSE 0 END) AS DIAS_ATRASO
FROM DBA.CONTAS_PAGAR CP
INNER JOIN DBA.CLIENTE_FORNECEDOR CF
    ON CF.IDCLIFOR = CP.IDCLIFOR
WHERE CP.IDEMPRESA IN ({{FILIAIS}})
  AND CP.FLAGBAIXADA = 'F'
GROUP BY CF.NOME
ORDER BY SALDO DESC
FETCH FIRST 40 ROWS ONLY;
