SELECT
    FP.DESCRRECEBIMENTO AS FORMA_PAGAMENTO,
    CAST(SUM(CR.VALTITULO - COALESCE(CR.SUMVALPAGAMENTOTITULO, 0) - COALESCE(CR.SUMVALDESCCONCEDIDOTITULO, 0)) AS NUMERIC(15,2)) AS SALDO
FROM DBA.CONTAS_RECEBER CR
INNER JOIN DBA.FORMA_PAGREC FP
    ON FP.IDRECEBIMENTO = CR.IDRECEBIMENTO
WHERE CR.IDEMPRESA IN ({{FILIAIS}})
  AND CR.FLAGBAIXADA = 'F'
GROUP BY FP.DESCRRECEBIMENTO
ORDER BY SALDO DESC
FETCH FIRST 15 ROWS ONLY;
