SELECT
    CF.NOME AS CLIENTE,
    COUNT(*) AS TITULOS,
    CAST(SUM(CR.VALTITULO - COALESCE(CR.SUMVALPAGAMENTOTITULO, 0) - COALESCE(CR.SUMVALDESCCONCEDIDOTITULO, 0)) AS NUMERIC(15,2)) AS SALDO,
    CAST(SUM(CASE WHEN CR.DTVENCIMENTO < CURRENT DATE
        THEN CR.VALTITULO - COALESCE(CR.SUMVALPAGAMENTOTITULO, 0) - COALESCE(CR.SUMVALDESCCONCEDIDOTITULO, 0)
        ELSE 0 END) AS NUMERIC(15,2)) AS VENCIDO,
    MAX(CASE WHEN CR.DTVENCIMENTO < CURRENT DATE THEN DAYS(CURRENT DATE) - DAYS(CR.DTVENCIMENTO) ELSE 0 END) AS DIAS_ATRASO
FROM DBA.CONTAS_RECEBER CR
INNER JOIN DBA.CLIENTE_FORNECEDOR CF
    ON CF.IDCLIFOR = CR.IDCLIFOR
WHERE CR.IDEMPRESA IN ({{FILIAIS}})
  AND CR.FLAGBAIXADA = 'F'
GROUP BY CF.NOME
ORDER BY SALDO DESC
FETCH FIRST 45 ROWS ONLY;
