WITH ABERTO AS (
    SELECT
        CP.IDEMPRESA,
        E.NOMEFANTASIA AS NOME_EMPRESA,
        CASE WHEN CP.DTVENCIMENTO < CURRENT DATE THEN 'Vencido' ELSE 'A vencer' END AS SITUACAO,
        CP.VALTITULO - COALESCE(CP.SUMVALPAGAMENTOTITULO, 0) - COALESCE(CP.SUMVALDESCCONCEDIDOTITULO, 0) AS SALDO
    FROM DBA.CONTAS_PAGAR CP
    INNER JOIN DBA.EMPRESA E
        ON E.IDEMPRESA = CP.IDEMPRESA
    WHERE CP.IDEMPRESA IN ({{FILIAIS}})
      AND CP.FLAGBAIXADA = 'F'
)
SELECT
    IDEMPRESA,
    NOME_EMPRESA,
    SITUACAO,
    CAST(SUM(SALDO) AS NUMERIC(15,2)) AS VALOR_SALDO
FROM ABERTO
GROUP BY IDEMPRESA, NOME_EMPRESA, SITUACAO
ORDER BY IDEMPRESA, SITUACAO;
