SELECT
    CASE WHEN CR.FLAGBAIXADA = 'T' THEN 'Baixado' ELSE 'Em aberto' END AS ESTADO,
    CASE WHEN CR.DTVENCIMENTO < CURRENT DATE THEN 'Vencido' ELSE 'A vencer' END AS SITUACAO,
    COUNT(*) AS TITULOS,
    CAST(SUM(CR.VALTITULO) AS NUMERIC(15,2)) AS VALOR,
    CAST(SUM(CR.VALTITULO - COALESCE(CR.SUMVALPAGAMENTOTITULO, 0) - COALESCE(CR.SUMVALDESCCONCEDIDOTITULO, 0)) AS NUMERIC(15,2)) AS SALDO
FROM DBA.CONTAS_RECEBER CR
WHERE CR.IDEMPRESA IN ({{FILIAIS}})
GROUP BY
    CASE WHEN CR.FLAGBAIXADA = 'T' THEN 'Baixado' ELSE 'Em aberto' END,
    CASE WHEN CR.DTVENCIMENTO < CURRENT DATE THEN 'Vencido' ELSE 'A vencer' END
ORDER BY ESTADO, SITUACAO;
