WITH DESPESAS AS (
    SELECT
        CASE
            WHEN PC.CLASSIFICACAO LIKE '42101%' THEN 'Vendas e logistica'
            WHEN PC.CLASSIFICACAO LIKE '42102%' THEN 'Administrativas'
            WHEN PC.CLASSIFICACAO LIKE '42103%' THEN 'Pessoal'
            WHEN PC.CLASSIFICACAO LIKE '42104%' THEN 'Tributarias'
            WHEN PC.CLASSIFICACAO LIKE '42105%' THEN 'Financeiras'
            WHEN PC.CLASSIFICACAO LIKE '42106%' THEN 'Ocupacao'
            WHEN PC.CLASSIFICACAO LIKE '42107%' THEN 'Marketing'
            WHEN PC.CLASSIFICACAO LIKE '42108%' THEN 'Depreciacao'
        END AS NATUREZA,
        VARCHAR_FORMAT(CS.DTMOVIMENTO, 'YYYY-MM') AS MES,
        CS.VALDEBITO - CS.VALCREDITO AS VALOR
    FROM DBA.CONTABIL_SALDO CS
    INNER JOIN DBA.CONTABIL_PLANO_CONTAS PC
        ON PC.IDCTACONTABIL = CS.IDCTACONTABIL
    WHERE CS.IDEMPRESA IN ({{FILIAIS}})
      AND CS.DTMOVIMENTO BETWEEN ? AND ?
      AND PC.TIPOCTACONTABIL = 'A'
      AND PC.CLASSIFICACAO LIKE '421%'
)
SELECT
    MES,
    NATUREZA,
    CAST(SUM(VALOR) AS NUMERIC(15,2)) AS VALOR_DESPESA
FROM DESPESAS
WHERE NATUREZA IS NOT NULL
GROUP BY MES, NATUREZA
ORDER BY MES, NATUREZA;
