WITH ULTIMA_DATA AS (
    SELECT
        IDEMPRESA,
        MAX(DTMOVIMENTO) AS DTMOVIMENTO
    FROM DBA.CONTABIL_SALDO
    WHERE IDEMPRESA IN ({{FILIAIS}})
      AND DTMOVIMENTO <= CURRENT DATE
    GROUP BY IDEMPRESA
),
SALDOS AS (
    SELECT
        CS.IDEMPRESA,
        E.NOMEFANTASIA AS NOME_EMPRESA,
        CASE WHEN PC.CLASSIFICACAO LIKE '11%' THEN CS.VALSALDOATUAL ELSE 0 END AS ATIVO_CIRCULANTE,
        CASE WHEN PC.CLASSIFICACAO LIKE '21%' THEN CS.VALSALDOATUAL ELSE 0 END AS PASSIVO_CIRCULANTE
    FROM DBA.CONTABIL_SALDO CS
    INNER JOIN ULTIMA_DATA UD
        ON UD.IDEMPRESA = CS.IDEMPRESA
        AND UD.DTMOVIMENTO = CS.DTMOVIMENTO
    INNER JOIN DBA.CONTABIL_PLANO_CONTAS PC
        ON PC.IDCTACONTABIL = CS.IDCTACONTABIL
        AND PC.TIPOCTACONTABIL = 'A'
    INNER JOIN DBA.EMPRESA E
        ON E.IDEMPRESA = CS.IDEMPRESA
    WHERE CS.IDEMPRESA IN ({{FILIAIS}})
      AND (PC.CLASSIFICACAO LIKE '11%' OR PC.CLASSIFICACAO LIKE '21%')
)
SELECT
    IDEMPRESA,
    NOME_EMPRESA,
    CASE
        WHEN SUM(PASSIVO_CIRCULANTE) = 0 THEN 0
        ELSE CAST(SUM(ATIVO_CIRCULANTE) AS NUMERIC(15,6)) / SUM(PASSIVO_CIRCULANTE)
    END AS LIQUIDEZ_CORRENTE
FROM SALDOS
GROUP BY IDEMPRESA, NOME_EMPRESA

UNION ALL

SELECT
    100 AS IDEMPRESA,
    'Todas as filiais' AS NOME_EMPRESA,
    CASE
        WHEN SUM(PASSIVO_CIRCULANTE) = 0 THEN 0
        ELSE CAST(SUM(ATIVO_CIRCULANTE) AS NUMERIC(15,6)) / SUM(PASSIVO_CIRCULANTE)
    END AS LIQUIDEZ_CORRENTE
FROM SALDOS

ORDER BY IDEMPRESA;
