WITH MOV AS (
    SELECT
        CS.IDEMPRESA,
        E.NOMEFANTASIA AS NOME_EMPRESA,
        CS.VALCREDITO - CS.VALDEBITO AS VALOR
    FROM DBA.CONTABIL_SALDO CS
    INNER JOIN DBA.CONTABIL_PLANO_CONTAS PC
        ON PC.IDCTACONTABIL = CS.IDCTACONTABIL
    INNER JOIN DBA.EMPRESA E
        ON E.IDEMPRESA = CS.IDEMPRESA
    WHERE CS.IDEMPRESA IN ({{FILIAIS}})
      AND CS.DTMOVIMENTO BETWEEN ? AND ?
      AND PC.TIPOCTACONTABIL = 'A'
      AND (PC.CLASSIFICACAO LIKE '31101%' OR PC.CLASSIFICACAO LIKE '31102%' OR PC.CLASSIFICACAO LIKE '31103%')
)
SELECT
    IDEMPRESA,
    NOME_EMPRESA,
    CAST(SUM(VALOR) AS NUMERIC(15,2)) AS RECEITA_LIQUIDA
FROM MOV
GROUP BY IDEMPRESA, NOME_EMPRESA

UNION ALL

SELECT
    100 AS IDEMPRESA,
    'Todas as filiais' AS NOME_EMPRESA,
    CAST(SUM(VALOR) AS NUMERIC(15,2)) AS RECEITA_LIQUIDA
FROM MOV

ORDER BY IDEMPRESA;
