WITH MOV AS (
    SELECT
        CS.IDEMPRESA,
        E.NOMEFANTASIA AS NOME_EMPRESA,
        PC.CLASSIFICACAO,
        PC.TIPONATUREZA,
        CS.VALDEBITO AS DEB,
        CS.VALCREDITO AS CRED
    FROM DBA.CONTABIL_SALDO CS
    INNER JOIN DBA.CONTABIL_PLANO_CONTAS PC
        ON PC.IDCTACONTABIL = CS.IDCTACONTABIL
    INNER JOIN DBA.EMPRESA E
        ON E.IDEMPRESA = CS.IDEMPRESA
    WHERE CS.IDEMPRESA IN ({{FILIAIS}})
      AND CS.DTMOVIMENTO BETWEEN ? AND ?
      AND PC.TIPOCTACONTABIL = 'A'
      AND (PC.CLASSIFICACAO LIKE '311%' OR PC.CLASSIFICACAO LIKE '312%'
           OR PC.CLASSIFICACAO LIKE '411%' OR PC.CLASSIFICACAO LIKE '421%')
),
POR_EMPRESA AS (
    SELECT
        IDEMPRESA,
        NOME_EMPRESA,
        CAST(SUM(CASE WHEN CLASSIFICACAO LIKE '31101%' OR CLASSIFICACAO LIKE '31102%' THEN CRED-DEB ELSE 0 END) AS NUMERIC(15,2)) AS RECEITA_BRUTA,
        CAST(SUM(CASE WHEN CLASSIFICACAO LIKE '31103%' THEN CRED-DEB ELSE 0 END) AS NUMERIC(15,2)) AS DEDUCOES,
        CAST(SUM(CASE WHEN CLASSIFICACAO LIKE '411%' THEN DEB-CRED ELSE 0 END) AS NUMERIC(15,2)) AS CMV,
        CAST(SUM(CASE WHEN CLASSIFICACAO LIKE '421%' AND CLASSIFICACAO NOT LIKE '42105%' THEN DEB-CRED ELSE 0 END) AS NUMERIC(15,2)) AS DESPESAS_OPERACIONAIS,
        CAST(SUM(CASE WHEN CLASSIFICACAO LIKE '31201%' THEN CRED-DEB ELSE 0 END) AS NUMERIC(15,2)) AS RECEITAS_FINANCEIRAS,
        CAST(SUM(CASE WHEN CLASSIFICACAO LIKE '42105%' THEN DEB-CRED ELSE 0 END) AS NUMERIC(15,2)) AS DESPESAS_FINANCEIRAS
    FROM MOV
    GROUP BY IDEMPRESA, NOME_EMPRESA
)
SELECT * FROM POR_EMPRESA

UNION ALL

SELECT
    100 AS IDEMPRESA,
    'Todas as filiais' AS NOME_EMPRESA,
    CAST(SUM(RECEITA_BRUTA) AS NUMERIC(15,2)),
    CAST(SUM(DEDUCOES) AS NUMERIC(15,2)),
    CAST(SUM(CMV) AS NUMERIC(15,2)),
    CAST(SUM(DESPESAS_OPERACIONAIS) AS NUMERIC(15,2)),
    CAST(SUM(RECEITAS_FINANCEIRAS) AS NUMERIC(15,2)),
    CAST(SUM(DESPESAS_FINANCEIRAS) AS NUMERIC(15,2))
FROM POR_EMPRESA

ORDER BY IDEMPRESA;
