WITH LUCRO_BASE AS (
    SELECT
        CASE
            WHEN EA.IDVENDEDOR IN (3529,3490,3491,3530,8904,134277) THEN 99
            ELSE E.IDEMPRESA
        END AS IDEMPRESA,
        CASE
            WHEN EA.IDVENDEDOR IN (3529,3490,3491,3530,8904,134277) THEN 'E-COMMERCE'
            ELSE E.NOMEFANTASIA
        END AS NOME_EMPRESA,
        CASE
            WHEN EA.TIPOBAIXAMESTRE='K' THEN
                (SELECT
                     CASE WHEN OI.TIPOMOVIMENTO='E' THEN 0
                          ELSE SUM(COALESCE(EST.VALLUCRO,0)*EST.QTDPRODUTO)
                     END
                 FROM DBA.ESTOQUE_ANALITICO EST
                 WHERE COALESCE(EST.NUMSEQUENCIAKIT,0)=EA.NUMSEQUENCIA
                   AND EST.IDPLANILHA=EA.IDPLANILHA
                   AND EST.IDSUBPRODUTO IN (
                       SELECT PK.IDSUBPRODUTO
                       FROM DBA.PRODUTO_KIT PK
                       WHERE PK.IDPRODUTOKIT=EA.IDPRODUTO
                         AND PK.IDSUBPRODUTOKIT=EA.IDSUBPRODUTO
                   )
                )
            ELSE
                CASE OI.TIPOMOVIMENTO
                     WHEN 'E' THEN 0
                     ELSE COALESCE(EA.VALLUCRO,0)*EA.QTDPRODUTO
                END
        END AS LUCROBRUTO
    FROM DBA.ESTOQUE_ANALITICO EA
    JOIN DBA.EMPRESA E ON E.IDEMPRESA=EA.IDEMPRESA
    JOIN DBA.NOTAS_ENTRADA_SAIDA NES ON NES.IDPLANILHA=EA.IDPLANILHA AND NES.IDEMPRESA=EA.IDEMPRESA AND NES.DTMOVIMENTO=EA.DTMOVIMENTO
    JOIN DBA.OPERACAO_INTERNA OI ON OI.IDOPERACAO=EA.IDOPERACAO
    WHERE COALESCE(EA.NUMSEQUENCIAKIT,0)<=0
      AND NES.TIPOITEMCATEGORIA NOT IN('D8')
      AND OI.FLAGMOVPRODUTOS='T'
      AND OI.TIPOMOVIMENTO IN ('V','E')
      AND EA.IDEMPRESA IN ({{FILIAIS}})
      AND EA.IDOPERACAO<>1301
      AND EA.DTMOVIMENTO BETWEEN ? AND ?
)
SELECT
    IDEMPRESA,
    NOME_EMPRESA,
    CAST(SUM(LUCROBRUTO) AS NUMERIC(15,6)) AS LUCRO_BRUTO
FROM LUCRO_BASE
GROUP BY IDEMPRESA, NOME_EMPRESA

UNION ALL

SELECT
    100 AS IDEMPRESA,
    'Todas as filiais' AS NOME_EMPRESA,
    CAST(SUM(LUCROBRUTO) AS NUMERIC(15,6)) AS LUCRO_BRUTO
FROM LUCRO_BASE

ORDER BY IDEMPRESA;
