WITH CUPONS_BASE AS (
    SELECT
        CASE
            WHEN EA.IDVENDEDOR IN (3529,3490,3491,3530,8904,134277) THEN 99
            ELSE E.IDEMPRESA
        END AS IDEMPRESA,
        CASE
            WHEN EA.IDVENDEDOR IN (3529,3490,3491,3530,8904,134277) THEN 'E-COMMERCE'
            ELSE E.NOMEFANTASIA
        END AS NOME_EMPRESA,
        CASE
            WHEN COALESCE(EA.NUMSEQUENCIAKIT,0) <= 0
                 AND OI.TIPOMOVIMENTO <> 'E'
            THEN EA.IDPLANILHA
            ELSE NULL
        END AS CUPOM
    FROM DBA.ESTOQUE_ANALITICO EA
    JOIN DBA.EMPRESA E ON E.IDEMPRESA = EA.IDEMPRESA
    JOIN DBA.NOTAS_ENTRADA_SAIDA NES ON NES.IDPLANILHA = EA.IDPLANILHA AND NES.IDEMPRESA = EA.IDEMPRESA AND NES.DTMOVIMENTO = EA.DTMOVIMENTO
    JOIN DBA.OPERACAO_INTERNA OI ON OI.IDOPERACAO = EA.IDOPERACAO
    WHERE EA.IDEMPRESA IN ({{FILIAIS}})
      AND EA.IDOPERACAO <> 1301
      AND EA.DTMOVIMENTO BETWEEN ? AND ?
)
SELECT
    IDEMPRESA,
    NOME_EMPRESA,
    COUNT(DISTINCT CUPOM) AS N_CUPONS
FROM CUPONS_BASE
GROUP BY IDEMPRESA, NOME_EMPRESA

UNION ALL

SELECT
    100 AS IDEMPRESA,
    'Todas as filiais' AS NOME_EMPRESA,
    COUNT(DISTINCT CUPOM) AS N_CUPONS
FROM CUPONS_BASE

ORDER BY IDEMPRESA;
