WITH ULTIMA_DATA AS (
    SELECT
        IDEMPRESA,
        MAX(DTMOVIMENTO) AS DTMOVIMENTO
    FROM DBA.ESTOQUE_SALDO_ATUAL
    WHERE IDEMPRESA IN ({{FILIAIS}})
      AND DTMOVIMENTO <= CURRENT DATE
    GROUP BY IDEMPRESA
),
ESTOQUE AS (
    SELECT
        ES.IDEMPRESA,
        E.NOMEFANTASIA AS NOME_EMPRESA,
        ES.VALATUALESTOQUE
    FROM DBA.ESTOQUE_SALDO_ATUAL ES
    INNER JOIN ULTIMA_DATA UD
        ON UD.IDEMPRESA = ES.IDEMPRESA
        AND UD.DTMOVIMENTO = ES.DTMOVIMENTO
    INNER JOIN DBA.EMPRESA E
        ON E.IDEMPRESA = ES.IDEMPRESA
    WHERE ES.IDEMPRESA IN ({{FILIAIS}})
)
SELECT
    IDEMPRESA,
    NOME_EMPRESA,
    CAST(SUM(VALATUALESTOQUE) AS NUMERIC(15,6)) AS VALOR_ESTOQUE
FROM ESTOQUE
GROUP BY IDEMPRESA, NOME_EMPRESA

UNION ALL

SELECT
    100 AS IDEMPRESA,
    'Todas as filiais' AS NOME_EMPRESA,
    CAST(SUM(VALATUALESTOQUE) AS NUMERIC(15,6)) AS VALOR_ESTOQUE
FROM ESTOQUE

ORDER BY IDEMPRESA;
