WITH DEVOLUCOES AS (
    SELECT
        CASE
            WHEN COALESCE(EA.IDVENDEDOR, 0) IN (3529,3490,3491,3530,8904,134277) THEN 99
            ELSE EA.IDEMPRESA
        END AS IDEMPRESA,
        CASE
            WHEN COALESCE(EA.IDVENDEDOR, 0) IN (3529,3490,3491,3530,8904,134277) THEN 'E-COMMERCE'
            ELSE E.NOMEFANTASIA
        END AS NOME_EMPRESA,
        CASE
            WHEN OI.TIPOMOVIMENTO = 'E' THEN EA.VALTOTLIQUIDO
            ELSE 0
        END AS VALOR
    FROM DBA.ESTOQUE_ANALITICO EA
    INNER JOIN DBA.NOTAS_ENTRADA_SAIDA NES
        ON NES.IDEMPRESA = EA.IDEMPRESA
        AND NES.IDPLANILHA = EA.IDPLANILHA
        AND NES.DTMOVIMENTO = EA.DTMOVIMENTO
    INNER JOIN DBA.NOTAS N
        ON N.IDEMPRESA = EA.IDEMPRESA
        AND N.IDPLANILHA = EA.IDPLANILHA
    INNER JOIN DBA.OPERACAO_INTERNA OI
        ON OI.IDOPERACAO = EA.IDOPERACAO
    INNER JOIN DBA.EMPRESA E
        ON E.IDEMPRESA = EA.IDEMPRESA
    WHERE
        EA.DTMOVIMENTO BETWEEN ? AND ?
        AND EA.IDEMPRESA IN ({{FILIAIS}})
        AND N.FLAGNOTACANCEL = 'F'
        AND OI.TIPOMOVIMENTO = 'E'
        AND COALESCE(EA.NUMSEQUENCIAKIT,0) <= 0
)
SELECT
    IDEMPRESA,
    NOME_EMPRESA,
    CAST(SUM(VALOR) AS NUMERIC(15,6)) AS VALOR_DEVOLUCOES
FROM DEVOLUCOES
GROUP BY IDEMPRESA, NOME_EMPRESA

UNION ALL

SELECT
    100 AS IDEMPRESA,
    'Todas as filiais' AS NOME_EMPRESA,
    CAST(SUM(VALOR) AS NUMERIC(15,6)) AS VALOR_DEVOLUCOES
FROM DEVOLUCOES

ORDER BY IDEMPRESA;
