WITH CANCELAMENTOS AS (
    SELECT
        NES.IDEMPRESA,
        E.NOMEFANTASIA AS NOME_EMPRESA,
        NES.VALCONTABIL AS VALOR
    FROM DBA.NOTAS_ENTRADA_SAIDA NES
    INNER JOIN DBA.NOTAS N
        ON NES.IDPLANILHA = N.IDPLANILHA
    INNER JOIN DBA.USUARIO U
        ON U.IDUSUARIO = N.IDUSUARIO
    INNER JOIN DBA.EMPRESA E
        ON E.IDEMPRESA = NES.IDEMPRESA
    WHERE NES.DTMOVIMENTO BETWEEN ? AND ?
        AND NES.IDEMPRESA IN ({{FILIAIS}})
        AND N.FLAGNOTACANCEL = 'T'
)
SELECT
    IDEMPRESA,
    NOME_EMPRESA,
    CAST(SUM(VALOR) AS NUMERIC(15,6)) AS VALOR_CANCELAMENTOS
FROM CANCELAMENTOS
GROUP BY IDEMPRESA, NOME_EMPRESA

UNION ALL

SELECT
    100 AS IDEMPRESA,
    'Todas as filiais' AS NOME_EMPRESA,
    CAST(SUM(VALOR) AS NUMERIC(15,6)) AS VALOR_CANCELAMENTOS
FROM CANCELAMENTOS

ORDER BY IDEMPRESA;
