WITH VENDAS AS (
    SELECT
        CASE
            WHEN EA.IDVENDEDOR IN (3529,3490,3491,3530,8904,134277) THEN 99
            ELSE E.IDEMPRESA
        END AS IDEMPRESA,
        CASE
            WHEN EA.IDVENDEDOR IN (3529,3490,3491,3530,8904,134277) THEN 'E-COMMERCE'
            ELSE E.NOMEFANTASIA
        END AS NOME_EMPRESA,
        CASE
            WHEN COALESCE(EA.NUMSEQUENCIAKIT,0) <= 0 THEN
                CASE OI.TIPOMOVIMENTO
                    WHEN 'E' THEN EA.VALTOTLIQUIDO * -1
                    ELSE EA.VALTOTLIQUIDO
                END
            ELSE 0
        END AS TOTALVENDA,
        CASE
            WHEN COALESCE(EA.NUMSEQUENCIAKIT,0) <= 0
                 AND OI.TIPOMOVIMENTO <> 'E'
            THEN EA.IDPLANILHA
            ELSE NULL
        END AS CUPOM
    FROM DBA.ESTOQUE_ANALITICO EA
    INNER JOIN DBA.NOTAS_ENTRADA_SAIDA NES
        ON NES.IDEMPRESA = EA.IDEMPRESA
        AND NES.IDPLANILHA = EA.IDPLANILHA
        AND NES.DTMOVIMENTO = EA.DTMOVIMENTO
    INNER JOIN DBA.NOTAS N
        ON N.IDEMPRESA = EA.IDEMPRESA
        AND N.IDPLANILHA = EA.IDPLANILHA
        AND N.FLAGNOTACANCEL = 'F'
    INNER JOIN DBA.OPERACAO_INTERNA OI
        ON OI.IDOPERACAO = EA.IDOPERACAO
        AND OI.FLAGMOVPRODUTOS = 'T'
        AND OI.TIPOMOVIMENTO IN ('V','E')
    INNER JOIN DBA.EMPRESA E
        ON E.IDEMPRESA = EA.IDEMPRESA
    WHERE
        EA.IDOPERACAO <> 1301
        AND EA.IDEMPRESA IN ({{FILIAIS}})
        AND NES.TIPOITEMCATEGORIA NOT IN ('D8')
        AND EA.DTMOVIMENTO BETWEEN ? AND ?
)
SELECT
    IDEMPRESA,
    NOME_EMPRESA,
    CASE
        WHEN COUNT(DISTINCT CUPOM) = 0 THEN 0
        ELSE CAST(SUM(TOTALVENDA) AS NUMERIC(15,6)) / COUNT(DISTINCT CUPOM)
    END AS TICKET_MEDIO
FROM VENDAS
GROUP BY IDEMPRESA, NOME_EMPRESA

UNION ALL

SELECT
    100 AS IDEMPRESA,
    'Todas as filiais' AS NOME_EMPRESA,
    CASE
        WHEN COUNT(DISTINCT CUPOM) = 0 THEN 0
        ELSE CAST(SUM(TOTALVENDA) AS NUMERIC(15,6)) / COUNT(DISTINCT CUPOM)
    END AS TICKET_MEDIO
FROM VENDAS

ORDER BY IDEMPRESA;
