SELECT FOTO FROM (
    SELECT PET.FOTOPRINCIPAL AS FOTO, 0 AS PRIORIDADE
    FROM DBA.PRODUTO_GRADE PG
    INNER JOIN DBA.PRODUTO_ESPECIFICACAO_TECNICA PET
        ON PET.IDCODBARPROD = PG.IDCODBARPROD
    WHERE PG.IDSUBPRODUTO = ?

    UNION ALL

    -- fallback: telas que só têm o código do produto "pai" (ex.: top produtos vendidos)
    -- pegam a foto de qualquer grade dele.
    SELECT PET.FOTOPRINCIPAL AS FOTO, 1 AS PRIORIDADE
    FROM DBA.PRODUTO_GRADE PG
    INNER JOIN DBA.PRODUTO_ESPECIFICACAO_TECNICA PET
        ON PET.IDCODBARPROD = PG.IDCODBARPROD
    WHERE PG.IDPRODUTO = ?
) T
ORDER BY PRIORIDADE
FETCH FIRST 1 ROWS ONLY;
