WITH VENDAS AS (
    SELECT
        EA.IDSUBPRODUTO,
        CASE
            WHEN COALESCE(EA.NUMSEQUENCIAKIT,0) <= 0 AND OI.TIPOMOVIMENTO <> 'E'
            THEN EA.QTDPRODUTO
            ELSE 0
        END AS QTDVENDA
    FROM DBA.ESTOQUE_ANALITICO EA
    INNER JOIN DBA.NOTAS_ENTRADA_SAIDA NES
        ON NES.IDEMPRESA = EA.IDEMPRESA
        AND NES.IDPLANILHA = EA.IDPLANILHA
        AND NES.DTMOVIMENTO = EA.DTMOVIMENTO
    INNER JOIN DBA.NOTAS N
        ON N.IDEMPRESA = EA.IDEMPRESA
        AND N.IDPLANILHA = EA.IDPLANILHA
        AND N.FLAGNOTACANCEL = 'F'
    INNER JOIN DBA.OPERACAO_INTERNA OI
        ON OI.IDOPERACAO = EA.IDOPERACAO
        AND OI.FLAGMOVPRODUTOS = 'T'
        AND OI.TIPOMOVIMENTO IN ('V','E')
    WHERE
        EA.IDVENDEDOR IN ({{VENDEDORES}})
        AND EA.IDOPERACAO <> 1301
        AND NES.TIPOITEMCATEGORIA NOT IN ('D8')
        AND EA.DTMOVIMENTO >= CURRENT DATE - 90 DAYS
)
SELECT
    PG.IDSUBPRODUTO AS CODIGO_PRODUTO,
    CAST(SUM(V.QTDVENDA) AS NUMERIC(15,3)) AS QUANTIDADE_VENDIDA
FROM VENDAS V
INNER JOIN DBA.PRODUTO_GRADE PG
    ON PG.IDSUBPRODUTO = V.IDSUBPRODUTO
    AND PG.FLAGINATIVO = 'F'
GROUP BY PG.IDSUBPRODUTO
HAVING SUM(V.QTDVENDA) > 0
ORDER BY QUANTIDADE_VENDIDA DESC
FETCH FIRST 40 ROWS ONLY;
