WITH ESTOQUE AS (
    SELECT
        IDPRODUTO,
        IDSUBPRODUTO,
        SUM(QTDATUALESTOQUE) AS QTDATUALESTOQUE
    FROM DBA.ESTOQUE_SALDO_ATUAL
    WHERE IDEMPRESA = 1
    GROUP BY IDPRODUTO, IDSUBPRODUTO
)
SELECT
    PG.IDSUBPRODUTO AS CODIGO_PRODUTO,
    P.DESCRCOMPRODUTO AS DESCRICAO,
    S.DESCRSECAO AS SECAO,
    PG.FLAGINATIVO AS INATIVO,
    PP.VALPRECOVAREJO AS PRECO,
    COALESCE(E.QTDATUALESTOQUE, 0) AS ESTOQUE
FROM DBA.PRODUTO_GRADE PG
INNER JOIN DBA.PRODUTO P
    ON P.IDPRODUTO = PG.IDPRODUTO
LEFT JOIN DBA.SECAO S
    ON S.IDSECAO = P.IDSECAO
LEFT JOIN DBA.POLITICA_PRECO_PRODUTO PP
    ON PP.IDPRODUTO = PG.IDPRODUTO
    AND PP.IDSUBPRODUTO = PG.IDSUBPRODUTO
    AND PP.IDEMPRESA = 1
LEFT JOIN ESTOQUE E
    ON E.IDPRODUTO = PG.IDPRODUTO
    AND E.IDSUBPRODUTO = PG.IDSUBPRODUTO
WHERE PG.IDSUBPRODUTO IN ({{CODIGOS}});
